### ISSUE TITLE
Sign in page

### ISSUE THREAD

**Issue by KevinLov** [AlexanderJarvheden/DD1367-Software-Engineering-in-Project-Form#10]
<img width="839" alt="Screenshot 2024-02-22 at 10 57 13" src="https://github.com/AlexanderJarvheden/DD1367-Software-Engineering-in-Project-Form/assets/58795082/28888206-bb84-46be-85b7-a8c298799b78">
Knappar  
**uppe på dashboard**  
- "loopbox" - Home - Contact -  Sign Up - Log in  

**Resten av skärmen**  
- Text input ruta: "Name"
- Text input ruta: "Email"
- Text input ruta: "Password"
- Text input ruta: "Phone number" ? kanske skipp på denna nu i början?
- "Sign up"

**Comment by AlexanderJarvheden** [comment]
Frontend part finished, onclick functions missing
